#!/usr/bin/env bash

# Configure generated runtime values after GCP bootstrap.
# This script does not create infrastructure and never replaces external
# credentials with placeholders.
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
ENV_MODE="${1:-}"
APPLY=false

if [[ "$ENV_MODE" != "dev" && "$ENV_MODE" != "prod" ]]; then
    echo "Usage: $0 [dev|prod] [--apply|--dry-run]" >&2
    exit 1
fi

for arg in "$@"; do
    case "$arg" in
        --apply) APPLY=true ;;
        --dry-run) APPLY=false ;;
        dev|prod) ;;
        *) echo "Unknown argument: $arg" >&2; exit 1 ;;
    esac
done

if [[ "$APPLY" == true ]]; then
    export DRY_RUN=false
else
    export DRY_RUN=true
fi

ENV_FILE=""
for candidate in \
    "${VIRTUAL_ENV:-}/../keys.env.${ENV_MODE}" \
    "$ROOT_DIR/../../power_core/keys.env.${ENV_MODE}" \
    "$ROOT_DIR/../../keys.env.${ENV_MODE}"; do
    if [[ -f "$candidate" ]]; then
        ENV_FILE="$candidate"
        break
    fi
done

if [[ -z "$ENV_FILE" ]]; then
    echo "Environment file not found. Expected keys.env.${ENV_MODE} next to the virtualenv." >&2
    exit 1
fi

set -a
# shellcheck disable=SC1090
source "$ENV_FILE"
if [[ -f "$ROOT_DIR/names.env" ]]; then
    # shellcheck disable=SC1091
    source "$ROOT_DIR/names.env"
fi
set +a

# Recreate deterministic values so this script also works with an older names.env.
# shellcheck disable=SC1091
source "$ROOT_DIR/lib/utils.sh"
# shellcheck disable=SC1091
source "$ROOT_DIR/lib/naming_convention.sh"
generate_and_export_names "$ENV_MODE" "${ORG_PREFIX:?ORG_PREFIX is required}" "${APP_NAME:?APP_NAME is required}"
persist_generated_names "$ROOT_DIR/names.env"

GCP_PROJECT_ID="${GCP_PROJECT_ID:-${GEN_NAME_PROJECT}}"
GCP_PROJECT_NUMBER="${GCP_PROJECT_NUMBER:-}"
SEC_FULLSTACK_JSON_KEYS="${SEC_FULLSTACK_JSON_KEYS:-}"

if [[ -z "$SEC_DROPBOX" || -z "$SEC_FULLSTACK_JSON_KEYS" ]]; then
    echo "Secret names could not be resolved from generated names." >&2
    exit 1
fi

TMP_DIR="$(mktemp -d)"
trap 'rm -r -- "$TMP_DIR"' EXIT
FIRESTORE_PAYLOAD="$TMP_DIR/firestore.json"
FULLSTACK_PAYLOAD="$TMP_DIR/fullstack.json"
EXISTING_FULLSTACK="$TMP_DIR/existing-fullstack.json"

# Read the current payload before preparing a replacement. This preserves
# existing generated and external values on repeated --apply runs.
if [[ "$APPLY" == true ]] && gcloud secrets versions access latest \
    --secret="$SEC_FULLSTACK_JSON_KEYS" --project="$GCP_PROJECT_ID" \
    >"$EXISTING_FULLSTACK" 2>/dev/null; then
    :
else
    : > "$EXISTING_FULLSTACK"
fi

export GCP_PROJECT_ID GCP_PROJECT_NUMBER SEC_DROPBOX SEC_FULLSTACK_JSON_KEYS
export APP_JSON_KEYS="${APP_JSON_KEYS:-$SEC_FULLSTACK_JSON_KEYS}"
export GCP_BUCKET_NAME="${GCP_BUCKET_NAME:-$GEN_NAME_BUCKET}"
export GCS_PUB_OUTPUT_BUCKET="${GCS_PUB_OUTPUT_BUCKET:-$GEN_NAME_PUB_OUTPUT_BUCKET}"
export GCS_PUB_INPUT_BUCKET="${GCS_PUB_INPUT_BUCKET:-$GEN_NAME_PUB_INPUT_BUCKET}"
export DROPBOX_TOPIC_NAME="${DROPBOX_TOPIC_NAME:-$GEN_NAME_DROPBOX_TOPIC}"
export GCP_TOPIC_NAME="${GCP_TOPIC_NAME:-$GEN_NAME_TOPIC}"
export S_ACCOUNT_RUN="${S_ACCOUNT_RUN:-$SA_EMAIL_3}"
export S_ACCOUNT_DROPBOX="${S_ACCOUNT_DROPBOX:-$SA_EMAIL_1}"
export STRAVA_UPLOAD="${STRAVA_UPLOAD:-disable}"
export EMAIL_MODE="${EMAIL_MODE:-local}"

python3 - "$FIRESTORE_PAYLOAD" "$FULLSTACK_PAYLOAD" "$EXISTING_FULLSTACK" <<'PY'
import json
import os
import secrets
import sys

firestore_path, fullstack_path, existing_path = sys.argv[1:]

def value(name, default=None):
    current = os.environ.get(name)
    return current if current not in (None, "") else default

# These values are generated by bootstrap and are safe for Firestore.
firestore = {
    "CS_BUCKET_NAME": value("CS_BUCKET_NAME", value("GCP_BUCKET_NAME")),
    "GCS_PUB_INPUT_BUCKET": value("GCS_PUB_INPUT_BUCKET"),
    "GCS_PUB_OUTPUT_BUCKET": value("GCS_PUB_OUTPUT_BUCKET"),
    "DROPBOX_TOPIC_NAME": value("DROPBOX_TOPIC_NAME"),
    "EMAIL_MODE": value("EMAIL_MODE", "local"),
    "LOGGING_LEVEL": value("LOGGING_LEVEL", "DEBUG"),
}

# Generated values are prepared here, while external credentials remain absent
# until the user supplies them through the documented secret setup flow.
fullstack_names = (
    "GCP_PROJECT_ID", "GCP_PROJECT_NUMBER", "S_ACCOUNT_RUN",
    "S_ACCOUNT_DROPBOX", "SEC_DROPBOX", "APP_JSON_KEYS", "GCP_TOPIC_NAME",
    "DROPBOX_TOPIC_NAME", "CLOUD_RUN_SERVICE", "CLOUD_RUN_SERVICE_PUB",
    "EVENTARC_SA", "EVENTARC_TRIGGER", "GCS_BUCKET_NAME",
    "GCS_PUB_OUTPUT_BUCKET", "EMAIL_MODE", "STRAVA_UPLOAD",
    "FLASK_SECRET_KEY", "PRIVATE_UPLOAD_TOKEN", "FRONTEND_BASE_URL",
    "DROpbox_WEBHOOK_PATH", "BREVO_API_KEY", "SENDER_EMAIL", "SENDER_NAME",
)
fullstack = {}
try:
    existing = json.load(open(existing_path))
    if isinstance(existing, dict):
        fullstack.update(existing)
except (FileNotFoundError, json.JSONDecodeError, TypeError):
    pass

for name in fullstack_names:
    current = value(name)
    if current:
        fullstack[name] = current

# These application secrets can be generated safely for a new environment.
fullstack.setdefault("FLASK_SECRET_KEY", secrets.token_hex(32))
fullstack.setdefault("PRIVATE_UPLOAD_TOKEN", secrets.token_hex(32))
fullstack.setdefault("DROpbox_WEBHOOK_PATH", "/" + secrets.token_urlsafe(24))

json.dump(firestore, open(firestore_path, "w"), indent=2, sort_keys=True)
json.dump(fullstack, open(fullstack_path, "w"), indent=2, sort_keys=True)
PY

MISSING_REQUIRED="$(python3 - "$FULLSTACK_PAYLOAD" <<'PY'
import json
import sys

payload = json.load(open(sys.argv[1]))
required = (
    "GCP_PROJECT_ID", "S_ACCOUNT_RUN", "S_ACCOUNT_DROPBOX", "SEC_DROPBOX",
    "APP_JSON_KEYS", "GCP_TOPIC_NAME", "DROPBOX_TOPIC_NAME",
    "GCS_BUCKET_NAME", "GCS_PUB_OUTPUT_BUCKET", "PRIVATE_UPLOAD_TOKEN",
    "DROpbox_WEBHOOK_PATH", "FLASK_SECRET_KEY", "FRONTEND_BASE_URL",
    "STRAVA_UPLOAD",
)
print("\n".join(name for name in required if not payload.get(name)))
PY
)"

echo "Runtime configuration: $ENV_MODE"
echo "Project: $GCP_PROJECT_ID"
echo
if [[ "$APPLY" == true ]]; then
    echo "Generated values persisted in: $ROOT_DIR/names.env"
else
    echo "Generated values would be persisted in: $ROOT_DIR/names.env"
fi
echo "Firestore payload prepared: $FIRESTORE_PAYLOAD"
echo "Fullstack secret payload prepared with generated application values."
echo
echo "Values ready for fullstack-app-json-keys:"
python3 - "$FULLSTACK_PAYLOAD" <<'PY'
import json
import sys

for name in sorted(json.load(open(sys.argv[1]))):
    print(f"  [READY] {name}")
PY

if [[ -n "$MISSING_REQUIRED" ]]; then
    echo "Required application values still missing:"
    while IFS= read -r name; do
        [[ -n "$name" ]] && echo "  [MISSING] $name"
    done <<< "$MISSING_REQUIRED"
fi

echo "Dropbox/Strava secret still requires external credentials:"
echo "  DROPBOX_APP_KEY, DROPBOX_APP_SECRET, DROPBOX_REFRESH_TOKEN"
if [[ "${STRAVA_UPLOAD}" == "enable" ]]; then
    echo "  STRAVA_CLIENT_ID, STRAVA_CLIENT_SECRET, STRAVA_REFRESH_TOKEN"
else
    echo "  Strava upload is disabled for this environment."
fi
echo

if [[ "$APPLY" != true ]]; then
    echo "Dry run only. No Firestore document or Secret Manager version was changed."
    echo "Run with --apply to write generated runtime values."
    exit 0
fi

if [[ -n "$MISSING_REQUIRED" ]]; then
    echo "Cannot apply an incomplete fullstack-app-json-keys payload." >&2
    echo "Set the missing values in keys.env.${ENV_MODE} or the environment and re-run." >&2
    exit 1
fi

# Write Firestore document via REST API (gcloud firestore documents not available).
# Implemented as a standalone module: lib/firestore_writer.py
python3 "$ROOT_DIR/lib/firestore_writer.py" \
    --payload "$FIRESTORE_PAYLOAD" \
    --project "$GCP_PROJECT_ID" \
    --document-path "config/local/settings/data"

gcloud secrets versions add "$SEC_FULLSTACK_JSON_KEYS" \
    --data-file="$FULLSTACK_PAYLOAD" \
    --project="$GCP_PROJECT_ID"

echo
echo "Runtime values written successfully."
echo "Dropbox/Strava credentials must be added to: $SEC_DROPBOX"
