#!/bin/bash
# =============================================================================
# power_core_run.sh — Submit Cloud Build for the 'power_core' service.
#
# PREREQUISITES:
#   - keys.env loaded (via venv activate or manually) containing:
#       GCP_PROJECT_ID, REGION, ARTIFACT_REGISTRY, CLOUD_RUN_SERVICE,
#       SA_DEPLOYER_EMAIL, GCS_BUILD_BUCKET, and all _-prefixed substitution vars.
#
# LOCAL DEVELOPMENT (instead of sourcing keys.env directly):
#   Use the Secret Manager emulator + local_dev.sh:
#     1. ./local_dev.sh start       # starts emulator + seeds secrets
#     2. source <(./local_dev.sh env)  # exports SM emulator env vars
#     3. python power_core/main.py  # app reads secrets from emulator
#
#   This keeps local dev closer to production (Secret Manager) without
#   requiring real GCP credentials or keys.env for secret values.
# =============================================================================
set -e

# --- Parse environment argument (optional, auto-detected from branch if not provided) ---
ENV_MODE="${1:-auto}"  # Default to auto-detect from branch
if [[ "$ENV_MODE" != "prod" && "$ENV_MODE" != "dev" && "$ENV_MODE" != "auto" ]]; then
    echo "❌ ERROR: Invalid environment '$ENV_MODE'. Use 'prod', 'dev', or 'auto'."
    echo "Usage: $0 [prod|dev|auto]"
    exit 1
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

VENV_PATH="$SCRIPT_DIR/.venv"

# Check if the activation script exists
if [ -f "$VENV_PATH/bin/activate" ]; then
    echo "Activating virtual environment..."
    # Sourcing the activate script makes the service-local python available.
    # Deploy config itself comes from keys.env.${ENV_MODE} below.
    # shellcheck disable=SC1091
    source "$VENV_PATH/bin/activate"
    echo "Virtual environment activated."
else
    echo "ERROR: Virtual environment activation script not found at $VENV_PATH/bin/activate." >&2
    # Use an exit code to indicate failure (as per best practice)
    exit 1
fi

# --- Auto-detect environment from branch ---
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "detached")
if [[ "$ENV_MODE" == "auto" ]]; then
    if [[ "$BRANCH_NAME" == "main" || "$BRANCH_NAME" == "master" ]]; then
        ENV_MODE="prod"
        echo "🔍 Auto-detected: main/master branch → PROD environment"
    else
        ENV_MODE="dev"
        echo "🔍 Auto-detected: feature branch '$BRANCH_NAME' → DEV environment"
    fi
fi

# Service-local env file (gitignored): <service>/keys.env.{dev,prod}
ENV_FILE="$SCRIPT_DIR/keys.env.${ENV_MODE}"
if [ ! -f "$ENV_FILE" ]; then
    echo "❌ ERROR: Environment file not found at $ENV_FILE. Aborting script."
    exit 1
fi

echo "Loading ${ENV_MODE} environment variables from $ENV_FILE..."
set -a
source "$ENV_FILE"
set +a

# Resource names already embed the environment (e.g. bigbikedata-dev-power-core-*),
# generated by the bootstrap naming convention. No -dev suffix is applied here.

# --- Branch-specific configuration ---
# Sanitized for Docker tags / Cloud Run names (lowercase, [a-z0-9_.-]).
# Equals BRANCH_NAME for normal branches (develop, testing); only previously
# failing names (feature/foo, detached HEAD) map to something deployable.
SAFE_BRANCH=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's#[^a-z0-9_.-]#-#g' | cut -c1-64)
SERVICE_SUFFIX=""
if [ "$SAFE_BRANCH" != "master" ] && [ "$SAFE_BRANCH" != "main" ] && [ "$SAFE_BRANCH" != "detached" ]; then
    SERVICE_SUFFIX="-$SAFE_BRANCH" # e.g., -testing
fi

TARGET_SERVICE_NAME="${CLOUD_RUN_SERVICE}${SERVICE_SUFFIX}"
# Unique tag per deploy: Artifact Registry immutable tags reject re-pushes of a
# fixed branch tag. Override with IMAGE_TAG_OVERRIDE=... when needed.
IMAGE_TAG="${IMAGE_TAG_OVERRIDE:-${SAFE_BRANCH}-$(date +%Y%m%d%H%M%S)}"

echo "Branch: $BRANCH_NAME"
echo "Target Service: $TARGET_SERVICE_NAME"
echo "Image Tag: $IMAGE_TAG"
echo "Environment: $ENV_MODE"
# ------------------------------------

echo "Dynamically building substitutions for Cloud Build..."
# --- Dynamic Substitution String Creation ---
SUBS=""
while IFS= read -r line || [[ -n "$line" ]]; do
    # Trim leading/trailing whitespace
    trimmed_line=$(echo "$line" | xargs)
    # Skip comments and empty lines
    if [[ "$trimmed_line" =~ ^\s*# || -z "$trimmed_line" ]]; then
        continue
    fi

    # Extract the variable name (part before the '=')
    key="${trimmed_line%%=*}"

    # Skip service/image names: they are (re-)added below with deploy targets.
    # Otherwise --substitutions would carry the same _KEY twice.
    case "$key" in
        CLOUD_RUN_SERVICE|CLOUD_RUN_SERVICE_PUB|YAML_IMAGE|YAML_IMAGE_PUB)
            continue
            ;;
    esac
    # Get the value of the variable from the already-sourced environment
    value="${!key}"

    # Append to the substitution string in the format _KEY=VALUE,
    SUBS+="_${key}=${value},"
done < "$ENV_FILE"

# Add/overwrite special substitutions for the build
SUBS+="_CLOUD_RUN_SERVICE=${TARGET_SERVICE_NAME},"
SUBS+="_YAML_IMAGE=${REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${ARTIFACT_REGISTRY}/${TARGET_SERVICE_NAME}:${IMAGE_TAG},"

# Strip trailing comma (gcloud rejects an empty trailing substitution entry).
SUBS="${SUBS%,}"

echo "Substitutions prepared."
# Vendor the shared gcp_actions lib into the build context (Docker COPY needs it
# inside the context). rsync excludes .git so we never upload VCS metadata.
LOCAL_DEP_PATH="$SCRIPT_DIR/../../gcp_actions"
# 2. Check if it exists to prevent vague errors later
if [ ! -d "$LOCAL_DEP_PATH" ]; then
    echo "❌ Error: Could not find dependency at $LOCAL_DEP_PATH"
    exit 1
fi
# 3. Copy it into the current directory so Cloud Build can see it
mkdir -p ./gcp_actions
rsync -a --exclude='.git' "$LOCAL_DEP_PATH/" ./gcp_actions
# ----------------------

# --- FIX 4: CONVERT DEPLOYER SA EMAIL TO FULL RESOURCE URL ---
# Assumes SA_NAME_DEPLOYER is set in keys.env (e.g., SA_NAME_DEPLOYER="bike-ci-deployer")
# And GCP_PROJECT_ID is set in keys.env

DEPLOYER_SA_RESOURCE_URL="projects/${GCP_PROJECT_ID}/serviceAccounts/${SA_DEPLOYER_EMAIL}"
DEPLOYER_BUCKET_URL="gs://${GCS_BUILD_BUCKET}/source-staging"
DEPLOYER_BUCKET_LOG="gs://${GCS_BUILD_BUCKET}/logs"

echo "Using Deployer SA Resource URL: $DEPLOYER_SA_RESOURCE_URL"
# -------------------------------------------------------------------


# Always remove the vendored copy, even when the build fails or we abort.
cleanup() { rm -rf ./gcp_actions; }
trap cleanup EXIT

echo "Submitting build from $SCRIPT_DIR (project: ${GCP_PROJECT_ID})..."
set +e
# --- Submit the Build ---
gcloud builds submit . \
    --project="${GCP_PROJECT_ID}" \
    --config=cloudbuild.yaml \
    --ignore-file=.dockerignore \
    --substitutions="${SUBS}" \
    --service-account="$DEPLOYER_SA_RESOURCE_URL" \
    --gcs-source-staging-dir="$DEPLOYER_BUCKET_URL"
BUILD_EXIT_CODE=$?
set -e

if [ $BUILD_EXIT_CODE -ne 0 ]; then
    echo "❌ Cloud Build failed (exit $BUILD_EXIT_CODE)."
    exit $BUILD_EXIT_CODE
fi
echo "✅ Cloud Build submitted successfully."