# site.yaml (Revised for Cloud Build substitutions)
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '${_YAML_IMAGE_PUB}', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_YAML_IMAGE_PUB}']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_CLOUD_RUN_SERVICE_PUB}'
      - '--image=${_YAML_IMAGE_PUB}'
      - '--region=${_REGION}'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--service-account=${_S_ACCOUNT_RUN}'
      - '--set-env-vars=GCP_PROJECT_ID=${_GCP_PROJECT_ID},GCS_BUCKET_NAME=${_GCS_BUCKET_NAME},GCS_PUB_INPUT_BUCKET=${_GCS_PUB_INPUT_BUCKET},GCS_PUB_OUTPUT_BUCKET=${_GCS_PUB_OUTPUT_BUCKET},CLOUD_RUN_SERVICE=${_CLOUD_RUN_SERVICE},BREVO_API_KEY=${_BREVO_API_KEY},EMAIL_MODE=${_EMAIL_MODE},GCP_TOPIC_NAME=${_GCP_TOPIC_NAME}'
      # Mount the Flask secret key from Secret Manager as an environment variable
      - '--set-secrets=FLASK_SECRET_KEY=FLASK_SECRET_KEY:latest'

images:
  - '${_YAML_IMAGE_PUB}'

# Add this option to allow unused variables from the .env file
options:
  substitution_option: 'ALLOW_LOOSE'
